server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.38.169.2:3306/common_pjt?serverTimezone=Asia/Seoul
    username: root
    password: 1234

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 357628841728-ca60bad81h8trvebct9a94upjm33usfb.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
              -
          facebook:
            client-id: 1893640937643897
            client-secret: 154fed3addf3912a7b4f3d4ec4c090ec
            scope:
              - email
              - public_profile

          naver:
#            client-id: 6dAmpqcANRi82B8m751p
#            client-secret: PY91U8BgkE
            client-id: V5gN96q3kFtGfUK7PUds
            client-secret: Z2RNeixHZU
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
        #            redirect-uri: http://localhost:3000/Api/Naver

        # naver? provider? ???? ???? ?? ?? ??? ?? provider ???? ??
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize # ??? ?????? ??
            token-uri: https://nid.naver.com/oauth2.0/token # ???? ?? ??
            user-info-uri: https://openapi.naver.com/v1/nid/me # ??? ??? ?? ??
            user-name-attribute: response # ????? json?? ??? response?? ???? ???? ????